### PR TITLE
Upgrades 20160119

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR has several upgrades and new additions. Also some reordering of commands for better caching. See Dockerfile for details.

### CODE REVIEW

**Comment by alimanfoo** [comment]
Not sure why there are conflicts, don't merge yet, I will try to fix.

**Comment by alimanfoo** [comment]
OK, conflicts resolved, ready to merge.

**Comment by alimanfoo** [comment]
Hold the merge, having some trouble with jupyter notebook...

**Comment by alimanfoo** [comment]
OK, this is good to go I think. I have updated the documentation and example script, including some info on how to get the notebook server running with HTTPS and a password. 

If this looks OK to you, could you merge and make a 1.3.0 release?

**Comment by hardingnj** [comment]
Great- thanks. The additions to the README are really helpful.

**Pull request merged**
